# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e7ee54906b32611dd52070f2c7e23d0e18c78dafb41a4ecfa9aa0162d5336ba6b4f6fa1863ea82c921ec6aabc59188977e14442b1c3462f11fd334e0a7b588

test:
  secret_key_base: a49748f31080ba23e7865f724f2a98ae4fa3ac14c18cb65622cd04d242e68adc4ca394ac48c413018d0628ad4d5f8dac685fbf39bf80929573a501636ffda0b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
